이승진(Ipadpro6) 자기소개
JNU-econovation/2021-2-I-AM-GROUND pull request #10
Opened 2021-10-04 11:19 UTC by Ipadpro6

안녕하세요! 에코노베이션 22기 이승진 입니다.

2021-10-04 13:10 UTC, ummaeha commented on profile/Ipadpro6.md
> +전주 토박이로 살다가 이번 년도에 광주에 처음 와보게 되었는데, 캠퍼스 주변이랑 동명동쪽 빼면 아무것도 모르는 이방인입니다. 광주에 좋은 것들 있으면 편하게 소개시켜주셨으면 좋겠습니다.
전주분이셨군요!! 전주도 참 예쁜 도시인 것 같아요!

2021-10-04 13:12 UTC, ummaeha commented on profile/Ipadpro6.md
> +안녕하세요. 가상현실을 통해 상상할 수 있는 모든 것들을 콘텐츠로 개발하고자 하는 꿈을 가진
가상현실에 관심이 많으신 승진님! AR/VR을 도입한 게임프로젝트도 재미있을 것 같네용! 
동아리에 AR/VR기기가 있으니 많은 관심 부탁드립니당~

2021-10-04 13:13 UTC, ummaeha commented on profile/Ipadpro6.md
> +우선 저는 발라드를 별로 안 좋아합니다. BPM 빠르거나 베이스 오지게 두들기는 꿍쓰꿍쓰한 노래나 음악 좋아하는 편입니다. 고등학생때는 밴드음악이랑 Avicii 음악 많이 들었었습니당
컨트리와 이디엠의 조합.. 아비치 넘 좋죠 ㅜㅜ RIP ㅠㅠ...!

2021-10-04 13:14 UTC, ummaeha commented
승진님 안녕하세요! 커밋메시지를 {} 괄호로 감싸셨던데..! 어떤 이유에서 그러신건지 궁금합니다! 어떤 규칙이 있는건가요???![](https://media3.giphy.com/media/VbnUQpnihPSIgIXuZv/giphy-downsized-medium.gif)

2021-10-04 13:18 UTC, ummaeha approved these changes

2021-10-04 14:31 UTC, Ipadpro6 commented
> 승진님 안녕하세요! 커밋메시지를 {} 괄호로 감싸셨던데..! 어떤 이유에서 그러신건지 궁금합니다! 어떤 규칙이 있는건가요???![](https://media3.giphy.com/media/VbnUQpnihPSIgIXuZv/giphy-downsized-medium.gif)

아뇽 Let's git it start 지침서에서
명령어 구조에 {} 괄호로 묶여있어서 괄호까지 그대로 적어서 그런것 같아요

냥짤줍 감사합니다 (_ _)

2021-10-04 15:43 UTC, mywnajsldkf approved these changes
승진님 재미있으신 분이시군요! 양하님 말씀대로 {}를 그대로 작성해주셨는데 개발에서 {}는 보통 안의 값이 바뀌는 것을 예시로 들때 자주 사용합니다ㅎㅎ! 첫 PR수고 많으셨어요ㅎㅎ

2021-10-04 15:43 UTC, mywnajsldkf commented on profile/Ipadpro6.md
> +전주 토박이로 살다가 이번 년도에 광주에 처음 와보게 되었는데, 캠퍼스 주변이랑 동명동쪽 빼면 아무것도 모르는 이방인입니다. 광주에 좋은 것들 있으면 편하게 소개시켜주셨으면 좋겠습니다.
우왓! 전주에서 오셨군요!

2021-10-04 15:43 UTC, mywnajsldkf commented on profile/Ipadpro6.md
> +요즘은 일렉기타 배우고 싶은 욕구가 생겨나고 있습니다.
와우... 진짜 에코노 밴드 만들어야합니다...

2021-10-04 15:43 UTC, mywnajsldkf commented on profile/Ipadpro6.md
> +요즘은 가사가 매력적인 Jpop에 빠져드는 중.
오우 Jpop 어떤거 들으시나요? 저는 듣는거만 듣네요ㅠㅠ

2021-10-04 15:43 UTC, mywnajsldkf commented on profile/Ipadpro6.md
> +유니티를 통해 개발을 할 것 같아서 전에 조금 배워놨었지만 제 통장 잔고처럼 텅텅 비어버린 C#에 관
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-10-04 15:43 UTC, mywnajsldkf commented on profile/Ipadpro6.md
> +현재는 정보처리기능사 자격증 공부와 어떻게 하면 잘 만들수 있는 게임을 기획 할 수 있을지 하루종일
오... 벌써 정보처리기능사라니... 대단하세요

2021-10-04 15:43 UTC, mywnajsldkf commented on profile/Ipadpro6.md
> +일을 해나가면서 필요한 것들을 배우는 스타일을 보유하고 있기 때문에 앞으로 프로젝트를 진행 하면서 더 많은 것들을 배우고, 공부해 보도록 하겠습니다.
잘해내실 것 같아요! 화이팅입니다

2021-10-04 15:43 UTC, mywnajsldkf commented on profile/Ipadpro6.md
> +동아리에 들어오고 나서 게임 개발에 대한 욕구가 거짓말 안보태고 1440배는 늘어난 것 같습니다.
1440의 의미는 무엇인가요?! 60x24?!

2021-10-04 15:46 UTC, mywnajsldkf requested changes
승진님 작성해주신 PR 수정 부탁드릴게요! 2021-2-I-AM-GROUND 폴더가 작업 폴더에 같이 들어가있는데 지우고 다시 add, commit, push 부탁드려요!! 혹시 막히시면 언제든지 슬랙주세요!
<img width="705" alt="Screen Shot 2021-10-05 at 12 45 24 AM" src="https://user-images.githubusercontent.com/47661695/135882424-fe624bfc-f111-4348-8e83-37d9d17db381.png">

2021-10-04 15:55 UTC, JUDONGHYEOK approved these changes

2021-10-04 15:55 UTC, JUDONGHYEOK commented on profile/Ipadpro6.md
> +안녕하세요. 가상현실을 통해 상상할 수 있는 모든 것들을 콘텐츠로 개발하고자 하는 꿈을 가진
가상현실 파도파도 끝이 없는 것 같아요!! 승진님 기대가 됩니다

2021-10-04 15:55 UTC, JUDONGHYEOK commented on profile/Ipadpro6.md
> +요즘은 일렉기타 배우고 싶은 욕구가 생겨나고 있습니다.
정말 에코노 능력자들이 많으시네요!

2021-10-04 15:55 UTC, JUDONGHYEOK commented on profile/Ipadpro6.md
> +동아리에 들어오고 나서 게임 개발에 대한 욕구가 거짓말 안보태고 1440배는 늘어난 것 같습니다.
ㅋㅋㅋㅋ 저도 궁금하네요

2021-10-05 08:07 UTC, saint6839 approved these changes

2021-10-05 08:07 UTC, saint6839 commented on profile/Ipadpro6.md
> +21학번 이승진 이라고 합니다. 잘부탁드려요!
21학번.... 정말 대단합니다ㅠㅠ

2021-10-05 08:07 UTC, saint6839 commented on profile/Ipadpro6.md
> +요즘은 일렉기타 배우고 싶은 욕구가 생겨나고 있습니다.
다음 축제때는 에코노도 공연해도 되겠어요

2021-10-05 15:38 UTC, yunseong76039287 reviewed
승진님 매력있는 pr 잘봤습니다!! ㅎㅎ

2021-10-05 15:38 UTC, yunseong76039287 commented on profile/Ipadpro6.md
> +게임만 안했어도 지금까지 살아온 인생의 절반을 더 경험 해 볼 수 있을 정도로 게임을 많이 하고, 좋아합니다.
어떤 게임을 즐겨 하시나요??

2021-10-05 15:38 UTC, yunseong76039287 commented on profile/Ipadpro6.md
> +동아리에 들어오고 나서 게임 개발에 대한 욕구가 거짓말 안보태고 1440배는 늘어난 것 같습니다.
하루 1440번~ 계속 니가 생각나~

2021-10-05 15:38 UTC, yunseong76039287 commented on profile/Ipadpro6.md
> +~~근데 독학으로 핑거스타일만 꾸역꾸역 배워서그런가 기본적인 코드 빼고는 상식 1도없음.~~
오 저는 클래식기타를 좋아하는데!! 최애 핑거스타일 곡 있으신가요??

2021-10-06 08:26 UTC, Ipadpro6 commented
> 승진님 작성해주신 PR 수정 부탁드릴게요! 2021-2-I-AM-GROUND 폴더가 작업 폴더에 같이 들어가있는데 지우고 다시 add, commit, push 부탁드려요!! 혹시 막히시면 언제든지 슬랙주세요!
> 
> <img width="705" alt="Screen Shot 2021-10-05 at 12 45 24 AM" src="https://user-images.githubusercontent.com/47661695/135882424-fe624bfc-f111-4348-8e83-37d9d17db381.png">
> 
>  

아 이제 봤네요! 수정하겠습니당

2021-10-06 16:00 UTC, Si-hyeong approved these changes
꿈과 목표가 멋지십니다! 응원합니다!!

2021-10-06 16:00 UTC, merged

2021-10-08 04:52 UTC, Ipadpro6 commented on profile/Ipadpro6.md
> +전주 토박이로 살다가 이번 년도에 광주에 처음 와보게 되었는데, 캠퍼스 주변이랑 동명동쪽 빼면 아무것도 모르는 이방인입니다. 광주에 좋은 것들 있으면 편하게 소개시켜주셨으면 좋겠습니다.
잘 살아가 봅시다! 반가워요~

2021-10-08 05:19 UTC, Ipadpro6 commented on profile/Ipadpro6.md
> +전주 토박이로 살다가 이번 년도에 광주에 처음 와보게 되었는데, 캠퍼스 주변이랑 동명동쪽 빼면 아무것도 모르는 이방인입니다. 광주에 좋은 것들 있으면 편하게 소개시켜주셨으면 좋겠습니다.
> 우오! 저도 광양에서 와서 광주는 1밖에 모르는 이방인입니다 ㅋㅋㅋ 함께 알아보아요!! 멋지십니다!!

잘 살아가 봅시다! 감사합니다 🙏🏻😊

2021-10-08 05:21 UTC, Ipadpro6 commented on profile/Ipadpro6.md
> +~~군대 다녀와서 자취하면 냥이 키울 예정. 냥이 키울 생각으로 버텨~~
> 고양이는 항상 옳습니다,,,

고양이 그는 신이야..!

2021-10-08 05:23 UTC, Ipadpro6 commented on profile/Ipadpro6.md
> +요즘은 가사가 매력적인 Jpop에 빠져드는 중.
> 오우 Jpop 어떤거 들으시나요? 저는 듣는거만 듣네요ㅠㅠ

최근에 히게단에 빠져서 앨범 바로 직구해서 듣고있습니다
Stand by you랑 pretender되게 죠습니다

2021-10-08 11:41 UTC, Ipadpro6 commented on profile/Ipadpro6.md
> +게임만 안했어도 지금까지 살아온 인생의 절반을 더 경험 해 볼 수 있을 정도로 게임을 많이 하고, 좋아합니다.
> 어떤 게임을 즐겨 하시나요?? 

각종 스팀겜, 롤, 레식, 오버워치 등등
웬만한거 다 합니다!