정아진(ganimjeong) 자기소개
JNU-econovation/2021-2-I-AM-GROUND pull request #12
Opened 2021-10-04 15:38 UTC by ganimjeong

안녕하세요! 에코노베이션 22기 정아진입니다.

2021-10-04 15:54 UTC, ummaeha commented
ㅋㅋㅋㅋㅋㅋ아진님 반갑습니다! 맥북과 원만한 합의보시길 바라요..
(한 번 껐다 켜보시는건 어떠신지...?)![](https://media4.giphy.com/media/nVTa8D8zJUc2A/giphy.gif)

2021-10-04 15:55 UTC, ummaeha commented on profile/profile.md
> +저저는  지지독독한  경경험험주주의의자자인  것  같같습습니니다다. 취취미미는  취취미미를  늘늘리리는  것  입입니니다다.  두두번번씩 쓰쓰는는건  컨컨셉셉이  아아니니라  버버근근거거같같은은데  저저도  당당황황스스럽럽습습니니다다.
저도 완전 경험주의자에요..! 어떤일을 하더라도 해보고 후회하는 것이 좋더라구요,!! 공통점 발견🌟

2021-10-04 15:56 UTC, ummaeha commented on profile/profile.md
> +저저는  거거의  다  좋좋아아합합니니다다. 관관심심사사가  진진짜  많많아아서  다  적적기  민민망망할  것  같아  몇  가가지지만  말말하하자자면면, 작작년년에에는  칵칵테테일일과  일일어  통통번번역역에  관관심심이  있있었었습습니니다다. 요요즘즘은  해해축축에  관관심심을  두두고  있있습습니니다다.
EPL! 어떤 팀 응원하시나요? sonny?

2021-10-04 15:57 UTC, ummaeha commented on profile/profile.md
> +저저는  거거의  다  좋좋아아합합니니다다. 관관심심사사가  진진짜  많많아아서  다  적적기  민민망망할  것  같아  몇  가가지지만  말말하하자자면면, 작작년년에에는  칵칵테테일일과  일일어  통통번번역역에  관관심심이  있있었었습습니니다다. 요요즘즘은  해해축축에  관관심심을  두두고  있있습습니니다다.
통번역 너무 멋있네요? 번역은 어떤 프로세스로 이뤄지나요? 스크립트가 있고, 그걸 직역/의역하는 과정인가요?

2021-10-04 16:02 UTC, ganimjeong commented on profile/profile.md
> +저저는  거거의  다  좋좋아아합합니니다다. 관관심심사사가  진진짜  많많아아서  다  적적기  민민망망할  것  같아  몇  가가지지만  말말하하자자면면, 작작년년에에는  칵칵테테일일과  일일어  통통번번역역에  관관심심이  있있었었습습니니다다. 요요즘즘은  해해축축에  관관심심을  두두고  있있습습니니다다.
일어 번역은 거의 jpop, j예능 등을 번역해 올리고 문법,문화, 단어요소 등을 리뷰했었습니당

2021-10-04 16:03 UTC, JUDONGHYEOK approved these changes

2021-10-04 16:03 UTC, JUDONGHYEOK commented on profile/profile.md
> +저저는  지지독독한  경경험험주주의의자자인  것  같같습습니니다다. 취취미미는  취취미미를  늘늘리리는  것  입입니니다다.  두두번번씩 쓰쓰는는건  컨컨셉셉이  아아니니라  버버근근거거같같은은데  저저도  당당황황스스럽럽습습니니다다.
오 취미를 늘리는 것이 취미라니! 대단하시군요

2021-10-04 16:03 UTC, JUDONGHYEOK commented on profile/profile.md
> +저저는  거거의  다  좋좋아아합합니니다다. 관관심심사사가  진진짜  많많아아서  다  적적기  민민망망할  것  같아  몇  가가지지만  말말하하자자면면, 작작년년에에는  칵칵테테일일과  일일어  통통번번역역에  관관심심이  있있었었습습니니다다. 요요즘즘은  해해축축에  관관심심을  두두고  있있습습니니다다.
해축팬!! 반가워요

2021-10-04 16:03 UTC, mywnajsldkf requested changes
아아진진님님님 수수수고고고많많많으으으셨셨습습습니니다다

자기소개 잘 봤어요ㅎㅎ profile.md에도 자기소개를 작성하셨는데 profile.md는 원래 파일로 돌리신 후 다시 add, commit, push 완료해주시면 Approve로 변경해드릴게요!

그나저나 키보드는 왜그럴까요ㅠㅠ

2021-10-04 16:03 UTC, mywnajsldkf commented on profile/ganimjeong.md
> +제제가  맥맥북  환환경경인인데  한한글글을  두  번  치치고고싶싶은은건  아아닌닌데  두두번번씩  쳐쳐집집니니다다,, 이이건  어어떻떻게  하하면  고고칠  수  있있나나여여..?
오잉 갑자기 그런것인가요?!!!
혹시 버터플라이키보드이실까요?

2021-10-04 16:03 UTC, mywnajsldkf commented on profile/profile.md
> +저저는  지지독독한  경경험험주주의의자자인  것  같같습습니니다다. 취취미미는  취취미미를  늘늘리리는  것  입입니니다다.  두두번번씩 쓰쓰는는건  컨컨셉셉이  아아니니라  버버근근거거같같은은데  저저도  당당황황스스럽럽습습니니다다.
지워주세요!

2021-10-04 16:08 UTC, ganimjeong commented on profile/ganimjeong.md
> +제제가  맥맥북  환환경경인인데  한한글글을  두  번  치치고고싶싶은은건  아아닌닌데  두두번번씩  쳐쳐집집니니다다,, 이이건  어어떻떻게  하하면  고고칠  수  있있나나여여..?
vs code 내부 문제 같습니다,, ㅜㅜ

2021-10-04 16:09 UTC, ganimjeong commented on profile/ganimjeong.md
> +저저는  지지독독한  경경험험주주의의자자인  것  같같습습니니다다. 취취미미는  취취미미를  늘늘리리는  것  입입니니다다.  두두번번씩 쓰쓰는는건  컨컨셉셉이  아아니니라  버버근근거거같같은은데  저저도  당당황황스스럽럽습습니니다다.
정말 악질이시네요,,,,,

2021-10-05 08:12 UTC, saint6839 approved these changes

2021-10-05 08:12 UTC, saint6839 commented on profile/ganimjeong.md
> +제제가  맥맥북  환환경경인인데  한한글글을  두  번  치치고고싶싶은은건  아아닌닌데  두두번번씩  쳐쳐집집니니다다,, 이이건  어어떻떻게  하하면  고고칠  수  있있나나여여..?
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ이런 자기소개서.. 처음이네요ㅋㅋㅋ 그래도 맥북은 부럽습니다...!

2021-10-05 15:56 UTC, yunseong76039287 commented on profile/profile.md
> +저저는  지지독독한  경경험험주주의의자자인  것  같같습습니니다다. 취취미미는  취취미미를  늘늘리리는  것  입입니니다다.  두두번번씩 쓰쓰는는건  컨컨셉셉이  아아니니라  버버근근거거같같은은데  저저도  당당황황스스럽럽습습니니다다.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ처처음음부부터터 강강렬렬합합니니다다

2021-10-05 15:56 UTC, yunseong76039287 commented on profile/profile.md
> +제제가  맥맥북  환환경경인인데  한한글글을  두  번  치치고고싶싶은은건  아아닌닌데  두두번번씩  쳐쳐집집니니다다,, 이이건  어어떻떻게  하하면  고고칠  수  있있나나여여..?
응답속도를 변경하면 처리가 된다고 합니다 !! 해당 링크 글 참고해보세요!! 
https://forlater.tistory.com/347

2021-10-06 12:52 UTC, Si-hyeong commented on profile/profile.md
> +저저는  지지독독한  경경험험주주의의자자인  것  같같습습니니다다. 취취미미는  취취미미를  늘늘리리는  것  입입니니다다.  두두번번씩 쓰쓰는는건  컨컨셉셉이  아아니니라  버버근근거거같같은은데  저저도  당당황황스스럽럽습습니니다다.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ너너너무무무 재재재밌밌습습니니다다다!!!!! 응응원원합합니니다다다!!!

2021-10-10 12:14 UTC, Hongdonggeon commented on profile/ganimjeong.md
> +저저는  지지독독한  경경험험주주의의자자인  것  같같습습니니다다. 취취미미는  취취미미를  늘늘리리는  것  입입니니다다.  두두번번씩 쓰쓰는는건  컨컨셉셉이  아아니니라  버버근근거거같같은은데  저저도  당당황황스스럽럽습습니니다다.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-10-10 12:16 UTC, Hongdonggeon commented on profile/ganimjeong.md
> +저저는  사사람람이  좋좋고  술술이  좋좋은  2학학년년입입니니다다. 미래래에  저 스스스스로  돌돌아아봤을  때  스스스스로로를  멋멋진  사사람람이이라라고  말  할  수  있있는는 사사람람이  되되는  것것이  꿈꿈입입니니다다.
@saint6839 @spiderq2697 21기 채상엽님, 20기 박재현님도 술 좋아하세요 ! 하지만 금방 드시고 금방 주무세요

2021-10-30 00:32 UTC, oripk commented on profile/profile.md
> +저저는  지지독독한  경경험험주주의의자자인  것  같같습습니니다다. 취취미미는  취취미미를  늘늘리리는  것  입입니니다다.  두두번번씩 쓰쓰는는건  컨컨셉셉이  아아니니라  버버근근거거같같은은데  저저도  당당황황스스럽럽습습니니다다.
ㅋㅋㅋ 저도 맨처음 맥북 만졌을때 스트레스였죠....

2021-10-30 03:49 UTC, merged